# Generated by Django 3.2.5 on 2021-07-27 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(verbose_name='finished'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
